### PR TITLE
Refactor, add {file} template

### LINKED ISSUE #191: Option to template filename in file.customTag
# Description

I would like to be able to template the file name in the file.customTag option.

I have set up the custom tag to include several section headers, as an outline for what I need to document per file. The first parameter of the section header needs to be a unique identifier for the heading (https://www.doxygen.nl/manual/commands.html#cmdsection), so I have taken to prefixing my section headers with the name of the file to avoid having several sections called "summary" and "history" etc.

Currently I need to do this manually. If there was a template such as {file} that allowed the filename to be automatically inserted, I could automate this process.

### PR DESCRIPTION
**Pull request by HO-COOH**
# Fix/Feature/Other

## Fix

- [ ] Link to issue. 
This closes #191 

## Feature
Add `{file}` template, so it can be used in `custom` tag of both file comments and generic comments.

## Other

- [ ] Description
I extracted some functionalities (mainly those `protected` implementation detail functions in `CppDocGen.ts`) to dedicated files to better reuse them, because they are not language dependent at the first place, as I am planning to add a backend that uses the language server.

I also tried to add documentation to those functions but they may not be accurate. Some function names are quite ambiguous to be honest.

### CODE REVIEW

**Comment by HO-COOH** [comment]
The backend I am talking about mainly uses `executeHoverProvider`. The hover result still needs to be parsed but will be simplified by language server. For example, macros will be replaced, types will be deduced etc.

**Comment by HO-COOH** [comment]
Don't know why the tests process get killed. It's passing all tests *and works on my machine*

**Comment by cschlosser** [comment]
>Don't know why the tests process get killed. It's passing all tests and works on my machine

The CI uses VS Code 1.56.0 now. Are you using 1.55.X locally by any chance?

> I also tried to add documentation to those functions but they may not be accurate. Some function names are quite ambiguous to be honest.

Thank you, yes I agree with you. But `util` isn't the most expressive name either 😉 

Ad language server:
What LS do you want to support? Does the C++ VSCode LS support this now reasonably?

I will review your changes in the upcomming days.

**Comment by HO-COOH** [comment]
>What LS do you want to support? Does the C++ VSCode LS support this now reasonably?
No it hasn't changed much. You either run another language server along side what the user already uses, which would be stupid or use vscode built-in command to query the user's language server, like `executeHoverProvider` I talked about, and then parse the result.

**Comment by HO-COOH** [comment]
I don't think that's the issue, and indeed I am using 1.56. 
The CI is failing at network connection this time.

**Review by cschlosser — CHANGES_REQUESTED** [review]
Please add a test for your changes.
Will merge it afterwards. CI is fine now too.

**Review by cschlosser — APPROVED** [review]

**Pull request merged**
